#ifndef _ERROR_H
#define _ERROR_H

#define ERR_SYSTEM_ERROR          10
#define ERR_INVALID_INSTRUCTION   20
#define ERR_INVALID_OPERAND       21
#define ERR_INVALID_INTEGER       41
#define ERR_INVALID_FLOAT         42
#define ERR_INVALID_OPERATOR      50
#define ERR_EXPECTING_INTEGER     51
#define ERR_EXPECTING_OPERATOR    52
#define NO_ERROR                 100
#define ERR_INVALID_DATA         101
#define ERR_LINKEDLIST_NULL      102
#define ERR_NULL_TOKEN           103
#define ERR_STACK_NULL           104
#define ERR_INVALID_ANSWER       105
#define ERR_INVALID_TOKENINFO    106
#define ERR_INVALID_TOKENTYPE    107
#define ERR_INVALID_AFFIX        108
#define ERR_INVALID_OPERATOR_TYPE 109
#define ERR_INVALID_TOKEN         110
#define ERR_STACK_INSUFFICIENT   111
#define ERR_STACK_NOT_EMPTY      112
#define ERR_INVALID_PRECEDENCE   113
#endif // _ERROR_H
